name: Deploy Landing Page

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main # Runs this workflow on every push to the 'main' branch.

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: m2b3/scicommons-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./landing-page
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: Transfer docker-compose.landing.yml to SERVER
        run: |
          scp -i ~/.ssh/id_rsa docker-compose.landing.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/ubuntu/deployment/docker-compose.landing.yml
      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            echo "Pulling the latest image..."
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:landing-page
            cd deployment/
            # Stop the current containers
            echo "Stopping the current containers..."
            docker compose -f docker-compose.landing.yml down || true
            # Start the containers using Docker Compose
            echo "Starting containers using Docker Compose..."
            docker compose -f docker-compose.landing.yml up -d --build
            echo "Cleaning up old images..."
            docker image prune -f
            echo "Deployment complete."
          EOF